/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.kit.snsop.beneficiary.enums;

/**
 *
 * @author anwar
 */
public enum HouseholdColumnEnum {
    STATE_NAME("State Name"),
    STATE_NAME_E("State Name"),
    COUNTY_NAME("County Name"),
    COUNTY_NAME_E("County Name"),
    PAYAM_NAME("Payam Name"),
    PAYAM_NAME_E("Payam Name"),
    BOMA_NAME("Boma Name"),
    BOMA_NAME_E("Boma Name"),
    HOUSEHOLD_NUMBER("Household Number"),
    RESPONDENT_FIRST_NAME("Respondent First Name"),
    RESPONDENT_FIRST_NAME_E("Respondent First Name"),
    RESPONDENT_MIDDLE_NAME("Respondent Middle Name"),
    RESPONDENT_MIDDLE_NAME_E("Respondent Middle Name"),
    RESPONDENT_LAST_NAME("Respondent Last Name"),
    RESPONDENT_LAST_NAME_E("Respondent Last Name"),
    RESPONDENT_NICK_NAME("Respondent Nick Name"),
    RESPONDENT_NICK_NAME_E("Respondent Nick Name"),
    RESPONDENT_RELATIONSHIP_HOUSEHOLD_HEAD("Respondent relationship to the household head"),
    RESPONDENT_RELATIONSHIP_HOUSEHOLD_HEAD_E("Respondent relationship to the household head"),
    AGE("Age"),
    AGE_E("Age"),
    RESPONDENT_GENDER("Respondent gender"),
    RESPONDENT_GENDER_E("Respondent gender"),
    HAS_ID("Do you have an ID"),
    HAS_ID_E("Do you have an ID"),
    ID_TYPE("What type of ID"),
    ID_TYPE_E("What type of ID"),
    ID_NUMBER("ID number"),
    ID_NUMBER_E("ID number"),
    RESPONDENT_PHONE_NUMBER("Respondent Phone Number"),
    RESPONDENT_PHONE_NUMBER_E("Respondent Phone Number"),
    HOUSEHOLD_MAIN_SOURCE_OF_INCOME("Household Main Source of Income"),
    HOUSEHOLD_MAIN_SOURCE_OF_INCOME_E("Household Main Source of Income"),
    HOUSEHOLD_MONTHLY_AVERAGE_INCOME("Household Monthly Average Income (In SSP)"),
    HOUSEHOLD_MONTHLY_AVERAGE_INCOME_E("Household Monthly Average Income (In SSP)"),
    RESPONDENT_MARITAL_STATUS("Respondent Marital Status"),
    RESPONDENT_MARITAL_STATUS_E("Respondent Marital Status"),
    RESPONDENT_LEGAL_STATUS("Respondent Legal Status"),
    RESPONDENT_LEGAL_STATUS_E("Respondent Legal Status"),
    SUPPORT_TYPE("Support type"),
    SUPPORT_TYPE_E("Support type"),
    REASON_FOR_SUPPORT_TYPE_1("Reason for support type 1"),
    REASON_FOR_SUPPORT_TYPE_1_E("Reason for support type 1"),
    REASON_FOR_SUPPORT_TYPE_2("Reason for support type 1"),
    REASON_FOR_SUPPORT_TYPE_2_E("Reason for support type 1"),
    REASON_FOR_SUPPORT_TYPE_3("Reason for support type 1"),
    REASON_FOR_SUPPORT_TYPE_3_E("Reason for support type 1"),
    REASON_FOR_SUPPORT_TYPE_4("Reason for support type 1"),
    REASON_FOR_SUPPORT_TYPE_4_E("Reason for support type 1"),
    REASON_FOR_SUPPORT_TYPE_5("Reason for support type 1"),
    REASON_FOR_SUPPORT_TYPE_5_E("Reason for support type 1"),
    HOUSEHOLD_SIZE("Household Size"),
    HOUSEHOLD_SIZE_E("Household Size"),
    TOTAL_MALES_0_2("Total males between 0-2 yrs"),
    TOTAL_MALES_0_2_E("Total males between 0-2 yrs"),
    TOTAL_MALES_3_5("Total males between 3-5 yrs"),
    TOTAL_MALES_3_5_E("Total males between 3-5 yrs"),
    TOTAL_MALES_6_17("Total males between 6-17 yrs"),
    TOTAL_MALES_6_17_E("Total males between 6-17 yrs"),
    TOTAL_MALES_18_35("Total males between 18-35 yrs"),
    TOTAL_MALES_18_35_E("Total males between 18-35 yrs"),
    TOTAL_MALES_36_64("Total males between 36-64 yrs"),
    TOTAL_MALES_36_64_E("Total males between 36-64 yrs"),
    TOTAL_MALES_65_ABOVE("Total males between 65 yrs or above"),
    TOTAL_MALES_65_ABOVE_E("Total males between 65 yrs or above"),
    TOTAL_FEMALES_0_2("Total females between 0-2 yrs"),
    TOTAL_FEMALES_0_2_E("Total females between 0-2 yrs"),
    TOTAL_FEMALES_3_5("Total females between 3-5 yrs"),
    TOTAL_FEMALES_3_5_E("Total females between 3-5 yrs"),
    TOTAL_FEMALES_6_17("Total females between 6-17 yrs"),
    TOTAL_FEMALES_6_17_E("Total females between 6-17 yrs"),
    TOTAL_FEMALES_18_35("Total females between 18-35 yrs"),
    TOTAL_FEMALES_18_35_E("Total females between 18-35 yrs"),
    TOTAL_FEMALES_36_64("Total females between 36-64 yrs"),
    TOTAL_FEMALES_36_64_E("Total females between 36-64 yrs"),
    TOTAL_FEMALES_65_ABOVE("Total females between 65 yrs or above"),
    TOTAL_FEMALES_65_ABOVE_E("Total females between 65 yrs or above"),
    DISABLED_MALES_0_2("Disabled males between 0-2 yrs"),
    DISABLED_MALES_0_2_E("Disabled males between 0-2 yrs"),
    DISABLED_MALES_3_5("Disabled males between 3-5 yrs"),
    DISABLED_MALES_3_5_E("Disabled males between 3-5 yrs"),
    DISABLED_MALES_6_17("Disabled males between 6-17 yrs"),
    DISABLED_MALES_6_17_E("Disabled males between 6-17 yrs"),
    DISABLED_MALES_18_35("Disabled males between 18-35 yrs"),
    DISABLED_MALES_18_35_E("Disabled males between 18-35 yrs"),
    DISABLED_MALES_36_64("Disabled males between 36-64 yrs"),
    DISABLED_MALES_36_64_E("Disabled males between 36-64 yrs"),
    DISABLED_MALES_65_ABOVE("Disabled males between 65 yrs or above"),
    DISABLED_MALES_65_ABOVE_E("Disabled males between 65 yrs or above"),
    DISABLED_FEMALES_0_2("Disabled females between 0-2 yrs"),
    DISABLED_FEMALES_0_2_E("Disabled females between 0-2 yrs"),
    DISABLED_FEMALES_3_5("Disabled females between 3-5 yrs"),
    DISABLED_FEMALES_3_5_E("Disabled females between 3-5 yrs"),
    DISABLED_FEMALES_6_17("Disabled females between 6-17 yrs"),
    DISABLED_FEMALES_6_17_E("Disabled females between 6-17 yrs"),
    DISABLED_FEMALES_18_35("Disabled females between 18-35 yrs"),
    DISABLED_FEMALES_18_35_E("Disabled females between 18-35 yrs"),
    DISABLED_FEMALES_36_64("Disabled females between 36-64 yrs"),
    DISABLED_FEMALES_36_64_E("Disabled females between 36-64 yrs"),
    DISABLED_FEMALES_65_ABOVE("Disabled females between 65 yrs or above"),
    DISABLED_FEMALES_65_ABOVE_E("Disabled females between 65 yrs or above"),
    CHRONICALLY_ILL_MALES_0_2("Chronically ill males between 0-2 yrs"),
    CHRONICALLY_ILL_MALES_0_2_E("Chronically ill males between 0-2 yrs"),
    CHRONICALLY_ILL_MALES_3_5("Chronically ill males between 3-5 yrs"),
    CHRONICALLY_ILL_MALES_3_5_E("Chronically ill males between 3-5 yrs"),
    CHRONICALLY_ILL_MALES_6_17("Chronically ill males between 6-17 yrs"),
    CHRONICALLY_ILL_MALES_6_17_E("Chronically ill males between 6-17 yrs"),
    CHRONICALLY_ILL_MALES_18_35("Chronically ill males between 18-35 yrs"),
    CHRONICALLY_ILL_MALES_18_35_E("Chronically ill males between 18-35 yrs"),
    CHRONICALLY_ILL_MALES_36_64("Chronically ill males between 36-64 yrs"),
    CHRONICALLY_ILL_MALES_36_64_E("Chronically ill males between 36-64 yrs"),
    CHRONICALLY_ILL_MALES_65_ABOVE("Chronically ill males between 65 yrs or above"),
    CHRONICALLY_ILL_MALES_65_ABOVE_E("Chronically ill males between 65 yrs or above"),
    CHRONICALLY_ILL_FEMALES_0_2("Chronically ill females between 0-2 yrs"),
    CHRONICALLY_ILL_FEMALES_0_2_E("Chronically ill females between 0-2 yrs"),
    CHRONICALLY_ILL_FEMALES_3_5("Chronically ill females between 3-5 yrs"),
    CHRONICALLY_ILL_FEMALES_3_5_E("Chronically ill females between 3-5 yrs"),
    CHRONICALLY_ILL_FEMALES_6_17("Chronically ill females between 6-17 yrs"),
    CHRONICALLY_ILL_FEMALES_6_17_E("Chronically ill females between 6-17 yrs"),
    CHRONICALLY_ILL_FEMALES_18_35("Chronically ill females between 18-35 yrs"),
    CHRONICALLY_ILL_FEMALES_18_35_E("Chronically ill females between 18-35 yrs"),
    CHRONICALLY_ILL_FEMALES_36_64("Chronically ill females between 36-64 yrs"),
    CHRONICALLY_ILL_FEMALES_36_64_E("Chronically ill females between 36-64 yrs"),
    CHRONICALLY_ILL_FEMALES_65_ABOVE("Chronically ill females between 65 yrs or above"),
    CHRONICALLY_ILL_FEMALES_65_ABOVE_E("Chronically ill females between 65 yrs or above"),
    BOTH_DISABLED_AND_CHRONICALLY_ILL_MALES_0_2("Both disabled and chronically ill males between 0-2 yrs"),
    BOTH_DISABLED_AND_CHRONICALLY_ILL_MALES_0_2_E("Both disabled and chronically ill males between 0-2 yrs"),
    BOTH_DISABLED_AND_CHRONICALLY_ILL_MALES_3_5("Both disabled and chronically ill males between 3-5 yrs"),
    BOTH_DISABLED_AND_CHRONICALLY_ILL_MALES_3_5_E("Both disabled and chronically ill males between 3-5 yrs"),
    BOTH_DISABLED_AND_CHRONICALLY_ILL_MALES_6_17("Both disabled and chronically ill males between 6-17 yrs"),
    BOTH_DISABLED_AND_CHRONICALLY_ILL_MALES_6_17_E("Both disabled and chronically ill males between 6-17 yrs"),
    BOTH_DISABLED_AND_CHRONICALLY_ILL_MALES_18_35("Both disabled and chronically ill males between 18-35 yrs"),
    BOTH_DISABLED_AND_CHRONICALLY_ILL_MALES_18_35_E("Both disabled and chronically ill males between 18-35 yrs"),
    BOTH_DISABLED_AND_CHRONICALLY_ILL_MALES_36_64("Both disabled and chronically ill males between 36-64 yrs"),
    BOTH_DISABLED_AND_CHRONICALLY_ILL_MALES_36_64_E("Both disabled and chronically ill males between 36-64 yrs"),
    BOTH_DISABLED_AND_CHRONICALLY_ILL_MALES_65_ABOVE("Both disabled and chronically ill males between 65 yrs or above"),
    BOTH_DISABLED_AND_CHRONICALLY_ILL_MALES_65_ABOVE_E("Both disabled and chronically ill males between 65 yrs or above"),
    BOTH_DISABLED_AND_CHRONICALLY_ILL_FEMALES_0_2("Both disabled and chronically ill females between 0-2 yrs"),
    BOTH_DISABLED_AND_CHRONICALLY_ILL_FEMALES_0_2_E("Both disabled and chronically ill females between 0-2 yrs"),
    BOTH_DISABLED_AND_CHRONICALLY_ILL_FEMALES_3_5("Both disabled and chronically ill females between 3-5 yrs"),
    BOTH_DISABLED_AND_CHRONICALLY_ILL_FEMALES_3_5_E("Both disabled and chronically ill females between 3-5 yrs"),
    BOTH_DISABLED_AND_CHRONICALLY_ILL_FEMALES_6_17("Both disabled and chronically ill females between 6-17 yrs"),
    BOTH_DISABLED_AND_CHRONICALLY_ILL_FEMALES_6_17_E("Both disabled and chronically ill females between 6-17 yrs"),
    BOTH_DISABLED_AND_CHRONICALLY_ILL_FEMALES_18_35("Both disabled and chronically ill females between 18-35 yrs"),
    BOTH_DISABLED_AND_CHRONICALLY_ILL_FEMALES_18_35_E("Both disabled and chronically ill females between 18-35 yrs"),
    BOTH_DISABLED_AND_CHRONICALLY_ILL_FEMALES_36_64("Both disabled and chronically ill females between 36-64 yrs"),
    BOTH_DISABLED_AND_CHRONICALLY_ILL_FEMALES_36_64_E("Both disabled and chronically ill females between 36-64 yrs"),
    BOTH_DISABLED_AND_CHRONICALLY_ILL_FEMALES_65_ABOVE("Both disabled and chronically ill females between 65 yrs or above"),
    BOTH_DISABLED_AND_CHRONICALLY_ILL_FEMALES_65_ABOVE_E("Both disabled and chronically ill females between 65 yrs or above"),
    CAN_RESPONDENT_READ_WRITE("Can respondent read and write?"),
    CAN_RESPONDENT_READ_WRITE_E("Can respondent read and write?"),
    HH_MEMBERS_18_35_READ_WRITE("How many members in the HH are between 18 and 35 and can read and write"),
    HH_MEMBERS_18_35_READ_WRITE_E("How many members in the HH are between 18 and 35 and can read and write"),
    LONGITUDE("Longitude"),
    LONGITUDE_E("Longitude"),
    LATITUDE("Latitude"),
    LATITUDE_E("Latitude"),
    FIRST_ALTERNATE("First Alternate"),
    FIRST_ALTERNATE_FIRST_NAME("First Name (1)"),
    FIRST_ALTERNATE_FIRST_NAME_E("First Name (1)"),
    FIRST_ALTERNATE_MIDDLE_NAME("Middle Name (1)"),
    FIRST_ALTERNATE_MIDDLE_NAME_E("Middle Name (1)"),
    FIRST_ALTERNATE_LAST_NAME("Last Name (1)"),
    FIRST_ALTERNATE_LAST_NAME_E("Last Name (1)"),
    FIRST_ALTERNATE_NICK_NAME("Nick Name (1)"),
    FIRST_ALTERNATE_NICK_NAME_E("Nick Name (1)"),
    FIRST_ALTERNATE_AGE("Age (1)"),
    FIRST_ALTERNATE_AGE_E("Age (1)"),
    FIRST_ALTERNATE_HAVE_ID("Do you have an ID (1)"),
    FIRST_ALTERNATE_HAVE_ID_E("Do you have an ID (1)"),
    FIRST_ALTERNATE_ID_TYPE("What type of ID (1)"),
    FIRST_ALTERNATE_ID_TYPE_E("What type of ID (1)"),
    FIRST_ALTERNATE_ID_NUMBER("ID number (1)"),
    FIRST_ALTERNATE_ID_NUMBER_E("ID number (1)"),
    FIRST_ALTERNATE_PHONE_NUMBER("Phone Number (1)"),
    FIRST_ALTERNATE_PHONE_NUMBER_E("Phone Number (1)"),
    FIRST_ALTERNATE_RELATIONSHIP("Relationship (1)"),
    FIRST_ALTERNATE_RELATIONSHIP_E("Relationship (1)"),
    FIRST_ALTERNATE_GENDER("Gender (1)"),
    FIRST_ALTERNATE_GENDER_E("Gender (1)"),
    SECOND_ALTERNATE("Second Alternate"),
    SECOND_ALTERNATE_FIRST_NAME("First Name (2)"),
    SECOND_ALTERNATE_FIRST_NAME_E("First Name (2)"),
    SECOND_ALTERNATE_MIDDLE_NAME("Middle Name (2)"),
    SECOND_ALTERNATE_MIDDLE_NAME_E("Middle Name (2)"),
    SECOND_ALTERNATE_LAST_NAME("Last Name (2)"),
    SECOND_ALTERNATE_LAST_NAME_E("Last Name (2)"),
    SECOND_ALTERNATE_NICK_NAME("Nick Name (2)"),
    SECOND_ALTERNATE_NICK_NAME_E("Nick Name (2)"),
    SECOND_ALTERNATE_AGE("Age (2)"),
    SECOND_ALTERNATE_AGE_E("Age (2)"),
    SECOND_ALTERNATE_HAVE_ID("Do you have an ID (2)"),
    SECOND_ALTERNATE_HAVE_ID_E("Do you have an ID (2)"),
    SECOND_ALTERNATE_ID_TYPE("What type of ID (2)"),
    SECOND_ALTERNATE_ID_TYPE_E("What type of ID (2)"),
    SECOND_ALTERNATE_ID_NUMBER("ID number (2)"),
    SECOND_ALTERNATE_ID_NUMBER_E("ID number (2)"),
    SECOND_ALTERNATE_PHONE_NUMBER("Phone Number (2)"),
    SECOND_ALTERNATE_PHONE_NUMBER_E("Phone Number (2)"),
    SECOND_ALTERNATE_RELATIONSHIP("Relationship (2)"),
    SECOND_ALTERNATE_RELATIONSHIP_E("Relationship (2)"),
    SECOND_ALTERNATE_GENDER("Gender (2)"),
    SECOND_ALTERNATE_GENDER_E("Gender (2)"),
    NOMINEES("Nominees"),
    HOUSEHOLD_PARTICIPATING("Would anyone in Household be interested in participating?"),
    HOUSEHOLD_PARTICIPATING_E("Would anyone in Household be interested in participating?"),
    NON_PARTICIPATING_REASON("Reason for why not"),
    NON_PARTICIPATING_REASON_E("Reason for why not"),
    NOMINEE_1_FIRST_NAME("Nominee_1 First Name"),
    NOMINEE_1_FIRST_NAME_E("Nominee_1 First Name"),
    NOMINEE_1_MIDDLE_NAME("Nominee_1 Middle Name"),
    NOMINEE_1_MIDDLE_NAME_E("Nominee_1 Middle Name"),
    NOMINEE_1_LAST_NAME("Nominee_1 Last Name"),
    NOMINEE_1_LAST_NAME_E("Nominee_1 Last Name"),
    NOMINEE_1_NICK_NAME("Nominee_1 Nick Name"),
    NOMINEE_1_NICK_NAME_E("Nominee_1 Nick Name"),
    NOMINEE_1_RELATIONSHIP_HOUSEHOLD_HEAD("Nominee_1 Relationship to the household head"),
    NOMINEE_1_RELATIONSHIP_HOUSEHOLD_HEAD_E("Nominee_1 Relationship to the household head"),
    NOMINEE_1_AGE("Nominee_1 Age"),
    NOMINEE_1_AGE_E("Nominee_1 Age"),
    NOMINEE_1_GENDER("Nominee_1 Gender"),
    NOMINEE_1_GENDER_E("Nominee_1 Gender"),
    NOMINEE_1_CAN_READ_AND_WRITE("Nominee_1 Does nominee read and write"),
    NOMINEE_1_CAN_READ_AND_WRITE_E("Nominee_1 Does nominee read and write"),
    NOMINEE_1_LIVELIHOOD("Nominee_1 What does nominee do for a living"),
    NOMINEE_1_LIVELIHOOD_E("Nominee_1 What does nominee do for a living"),

    NOMINEE_2_FIRST_NAME("Nominee_2 First Name"),
    NOMINEE_2_FIRST_NAME_E("Nominee_2 First Name"),
    NOMINEE_2_MIDDLE_NAME("Nominee_2 Middle Name"),
    NOMINEE_2_MIDDLE_NAME_E("Nominee_2 Middle Name"),
    NOMINEE_2_LAST_NAME("Nominee_2 Last Name"),
    NOMINEE_2_LAST_NAME_E("Nominee_2 Last Name"),
    NOMINEE_2_NICK_NAME("Nominee_2 Nick Name"),
    NOMINEE_2_NICK_NAME_E("Nominee_2 Nick Name"),
    NOMINEE_2_RELATIONSHIP_HOUSEHOLD_HEAD("Nominee_2 Relationship to the household head"),
    NOMINEE_2_RELATIONSHIP_HOUSEHOLD_HEAD_E("Nominee_2 Relationship to the household head"),
    NOMINEE_2_AGE("Nominee_2 Age"),
    NOMINEE_2_AGE_E("Nominee_2 Age"),
    NOMINEE_2_GENDER("Nominee_2 Gender"),
    NOMINEE_2_GENDER_E("Nominee_2 Gender"),
    NOMINEE_2_CAN_READ_AND_WRITE("Nominee_2 Does nominee read and write"),
    NOMINEE_2_CAN_READ_AND_WRITE_E("Nominee_2 Does nominee read and write"),
    NOMINEE_2_LIVELIHOOD("Nominee_2 What does nominee do for a living"),
    NOMINEE_2_LIVELIHOOD_E("Nominee_2 What does nominee do for a living"),
    
    NOMINEE_3_FIRST_NAME("Nominee_3 First Name"),
    NOMINEE_3_FIRST_NAME_E("Nominee_3 First Name"),
    NOMINEE_3_MIDDLE_NAME("Nominee_3 Middle Name"),
    NOMINEE_3_MIDDLE_NAME_E("Nominee_3 Middle Name"),
    NOMINEE_3_LAST_NAME("Nominee_3 Last Name"),
    NOMINEE_3_LAST_NAME_E("Nominee_3 Last Name"),
    NOMINEE_3_NICK_NAME("Nominee_3 Nick Name"),
    NOMINEE_3_NICK_NAME_E("Nominee_3 Nick Name"),
    NOMINEE_3_RELATIONSHIP_HOUSEHOLD_HEAD("Nominee_3 Relationship to the household head"),
    NOMINEE_3_RELATIONSHIP_HOUSEHOLD_HEAD_E("Nominee_3 Relationship to the household head"),
    NOMINEE_3_AGE("Nominee_3 Age"),
    NOMINEE_3_AGE_E("Nominee_3 Age"),
    NOMINEE_3_GENDER("Nominee_3 Gender"),
    NOMINEE_3_GENDER_E("Nominee_3 Gender"),
    NOMINEE_3_CAN_READ_AND_WRITE("Nominee_3 Does nominee read and write"),
    NOMINEE_3_CAN_READ_AND_WRITE_E("Nominee_3 Does nominee read and write"),
    NOMINEE_3_LIVELIHOOD("Nominee_3 What does nominee do for a living"),
    NOMINEE_3_LIVELIHOOD_E("Nominee_3 What does nominee do for a living"),
    
    NOMINEE_4_FIRST_NAME("Nominee_4 First Name"),
    NOMINEE_4_FIRST_NAME_E("Nominee_4 First Name"),
    NOMINEE_4_MIDDLE_NAME("Nominee_4 Middle Name"),
    NOMINEE_4_MIDDLE_NAME_E("Nominee_4 Middle Name"),
    NOMINEE_4_LAST_NAME("Nominee_4 Last Name"),
    NOMINEE_4_LAST_NAME_E("Nominee_4 Last Name"),
    NOMINEE_4_NICK_NAME("Nominee_4 Nick Name"),
    NOMINEE_4_NICK_NAME_E("Nominee_4 Nick Name"),
    NOMINEE_4_RELATIONSHIP_HOUSEHOLD_HEAD("Nominee_4 Relationship to the household head"),
    NOMINEE_4_RELATIONSHIP_HOUSEHOLD_HEAD_E("Nominee_4 Relationship to the household head"),
    NOMINEE_4_AGE("Nominee_4 Age"),
    NOMINEE_4_AGE_E("Nominee_4 Age"),
    NOMINEE_4_GENDER("Nominee_4 Gender"),
    NOMINEE_4_GENDER_E("Nominee_4 Gender"),
    NOMINEE_4_CAN_READ_AND_WRITE("Nominee_4 Does nominee read and write"),
    NOMINEE_4_CAN_READ_AND_WRITE_E("Nominee_4 Does nominee read and write"),
    NOMINEE_4_LIVELIHOOD("Nominee_4 What does nominee do for a living"),
    NOMINEE_4_LIVELIHOOD_E("Nominee_4 What does nominee do for a living"),

    NOMINEE_5_FIRST_NAME("Nominee_5 First Name"),
    NOMINEE_5_FIRST_NAME_E("Nominee_5 First Name"),
    NOMINEE_5_MIDDLE_NAME("Nominee_5 Middle Name"),
    NOMINEE_5_MIDDLE_NAME_E("Nominee_5 Middle Name"),
    NOMINEE_5_LAST_NAME("Nominee_5 Last Name"),
    NOMINEE_5_LAST_NAME_E("Nominee_5 Last Name"),
    NOMINEE_5_NICK_NAME("Nominee_5 Nick Name"),
    NOMINEE_5_NICK_NAME_E("Nominee_5 Nick Name"),
    NOMINEE_5_RELATIONSHIP_HOUSEHOLD_HEAD("Nominee_5 Relationship to the household head"),
    NOMINEE_5_RELATIONSHIP_HOUSEHOLD_HEAD_E("Nominee_5 Relationship to the household head"),
    NOMINEE_5_AGE("Nominee_5 Age"),
    NOMINEE_5_AGE_E("Nominee_5 Age"),
    NOMINEE_5_GENDER("Nominee_5 Gender"),
    NOMINEE_5_GENDER_E("Nominee_5 Gender"),
    NOMINEE_5_CAN_READ_AND_WRITE("Nominee_5 Does nominee read and write"),
    NOMINEE_5_CAN_READ_AND_WRITE_E("Nominee_5 Does nominee read and write"),
    NOMINEE_5_LIVELIHOOD("Nominee_5 What does nominee do for a living"),
    NOMINEE_5_LIVELIHOOD_E("Nominee_5 What does nominee do for a living");

    
    private final String fieldName;

    HouseholdColumnEnum(String fieldName) {
        this.fieldName = fieldName;
    }

    public String getFieldName() {
        return fieldName;
    }
}
